### ISSUE TITLE
failed: Error during WebSocket handshake: Unexpected response code: 403

### ISSUE THREAD

**Issue by aep** [aws-samples/aws-iot-examples#1]
doesnt look like that example still works

**Comment by bladepan** [comment]
Make sure endpoint matches region, you can find a region's endpoint by describeEndpoint command. And also check if the account you are using has the permission to connect to AWS IoT.

**Comment by ashishtilara** [comment]
+1,

I am having the same issue, I double checked the credentials and endpoint, but its not connecting to MQTT correctly.
![screen shot 2016-07-06 at 3 10 27 pm](https://cloud.githubusercontent.com/assets/1509613/16608097/e17bddfe-438b-11e6-9848-7c01f1fc04d5.png)

I tried to use same endpoint with TruckSimulator, and that works without any issues.

**Comment by bladepan** [comment]
I just checked the example and it works. @ashishtilara does your IAM policy of the access key allows Iot related actions? Like in my IAM user, the policy is 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:Connect",
                "iot:Publish",
                "iot:Subscribe",
                "iot:Receive",
                "iot:GetThingShadow",
                "iot:UpdateThingShadow"
            ],
            "Resource": "*"
       }
    ]
}
```

And you can also use this page https://www.websocket.org/echo.html to test if your browser supports WebSocket communication.

**Comment by ashishtilara** [comment]
Hi @bladepan, I have following setup in my IAM user,

```
 {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1467781086000",
            "Effect": "Allow",
            "Action": [
                "iot:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

Also I am using Chrome Version 51.0.2704.103 (64-bit), and it supports WebSocket Communication.

**Comment by ashishtilara** [comment]
MQTT Client Example still doesn't seem to be working, I tried to use it with a different account and machine, and I am seeing same behaviour. This time I am using Root Key and Chrome Version 52.0.2743.116 (64-bit). 

What I am trying is, setting up a gateway connection with client ID and subscribing to a topic in AWS Console and Using same client ID and Topic in this example, and that's when it fails to connect.

**Comment by TheRyanBurke** [comment]
@ashishtilara are you using the same client ID in two different MQTT clients at the same time? This is not supported per the specification. Does it work if you differentiate the client IDs between AWS console and the sample app?

**Comment by TheRyanBurke** [comment]
For those having issues with 403 response in the WebSocket, be sure to serve the file from a web service and not opening the file directly from local file system. For example, [Python's simple HTTP service](https://docs.python.org/2/library/simplehttpserver.html).

**Comment by ab99484** [comment]
@TheRyanBurke 
Would you please explain how can I get AWS session token?
[https://github.com/aws-samples/aws-iot-examples/blob/master/deviceSimulator/createResources.js#L10](url)
